### ISSUE TITLE
Toggle Controls -> Direct Controls

### ISSUE THREAD

**Issue by echoictech** [AndyEngland521/Laptop#3]
In ```bluetoothInterface``` we see that some commands toggle depending on the existing state of the system. This means that to guarantee setting these characteristics requires a read to determine the existing state. This increases complexity for controllers.

Is it too late to change the format of these commands to direct control? Here are suggested changes:

Characteristic | Current Control | Suggested Control
--- | --- | ---
Audio Source | ```'m'``` | ```'m0-1'``` 
Audio Reactivity | ```'A'``` | ```'A0-1'``` 
Blending | ```'B'``` | ```'B0-1'```

**Comment by AndyEngland521** [comment]
We can totally do this, makes perfect sense

**Comment by AndyEngland521** [comment]
Audio Source: `mm` is mic and `mj` is jack
Audio Reactivity and Blending I've followed your suggestions.
